/*SQL Questions 
1.	Write a SQL query to find the second highest salary from the employee table:
We can achieve it in 2 ways:
--1)	Using Max() aggregate function + subquery concept:*/
select max(salary) from employee 
where salary < (select max(salary) from employee);
--2)	Using window function:
Select emp_id, emp_name, salary from (select emp_id, emp_name, salary,
Dense_rank() over(order by salary desc) as rank from employee) t 
Where rank = 2;

--2.	Find departments whose average salary is greater than 60,000:
Select department, avg(salary) as avg_salary from employee group by department having avg(salary) > 60000;

--3.	Find customers who have never placed an order:
--Tables: customers, orders
Select c.customer_name, o.customer_id from customers c
Left join orders o on c.customer_id = o.customer_id
Where o.customer_id is null;

--4.	Find the employee who has the highest salary in each department.
Select emp_id, emp_name, salary from (select emp_id, emp_name, salary, dense_rank() over(partition by department order by salary desc) as rank from employee) t where rank = 1;

--5.	Find employees whose salary is greater than the average salary of their own department:
Select emp_name, department, salary from( select  emp_name, department, salary, avg(salary) over(partition by department) as avg_salary from employee)t where salary > avg_salary;

--6.	Find the top 2 highest-paid employees from each department. 
--Expected columns: department, emp_name, salary, rank
	Select emp_name, department, salary, rnk as rank from (select emp_name, department, salary, dense_rank() over(partition by department order by salary desc) as rnk from employee)t where rnk <= 2;

--7.	Calculate the total sales for each month:
Select year(order_date) AS year, month(order_date) AS month,sum(amount) AS total_sales from orders group by year(order_date), month(order_date)
order by year, month;

--8.	Calculate the total order amount for each customer and return only customers whose total spending is greater than the average customer spending. 
--Expected columns: customer_id customer_name total_spent:
WITH customer_totals AS (
    select c.customer_id, c.customer_name, SUM(o.amount) AS total_spent
    from customers c
    join orders o ON c.customer_id = o.customer_id
    group by c.customer_id, c.customer_name
)
select customer_id, customer_name, total_spent
from customer_totals
where total_spent > ( select AVG(total_spent) from customer_totals );

--9.	Find employees whose salary is higher than the previous employee's salary based on   emp_id. 
--Expected columns: emp_id emp_name salary previous_salary
WITH employee_salary AS (
    select emp_id, emp_name, salary,
    LAG(salary) OVER (ORDER BY emp_id) AS previous_salary
    from employees
)
select emp_id, emp_name, salary, previous_salary
from employee_salary
where salary > previous_salary;

--10.	Find the department having the highest total salary expenditure. 
--Expected columns: department total_salary:
WITH department_salary AS (
    select department, SUM(salary) AS total_salary
    from employees
    group by department
)
select department, total_salary
from department_salary
where total_salary = ( select MAX(total_salary) from department_salary);

--11.	Find all email addresses that are registered for more than one customer. 
--Expected columns: email customer_count:
select email, COUNT(*) AS customer_count
from customers
group by email
having count(*) > 1;

--12.	Find the number of employees who joined in each year. 
--Expected columns: joining_year employee_count:
select year(joining_date) AS joining_year, COUNT(*) AS employee_count
from employees
group by YEAR(joining_date)
order by joining_year;

--13.	Find products that have never been sold. 
--Expected columns: product_id product_name:
select p.product_id, p.product_name
from products p
left join sales s ON p.product_id = s.product_id
where s.product_id IS NULL;

--14.	Calculate the total revenue generated by each product. 
--Formula: Revenue = price × quantity:
select p.product_name, SUM(s.quantity) AS total_quantity, SUM(p.price * s.quantity) AS total_revenue
from products p
join sales s ON p.product_id = s.product_id
group by p.product_id, p.product_name;

--15.	Display each employee along with their manager's name. 
--Expected columns: employee_name manager_name:
select e.emp_name AS employee_name, m.emp_name AS manager_name
from employees e
left join employees m ON e.manager_id = m.emp_id;

--16.	Find employees who do not have a manager. 
--Expected columns: emp_id emp_name:
select emp_id, emp_name
from employees
where manager_id IS NULL;

--17.	Find the number of employees reporting directly to each manager. 
--Expected columns: manager_id employee_count:
select manager_id, COUNT(*) AS employee_count
from employees
where manager_id IS NOT NULL
group by manager_id;

--18.	Find the missing employee ID between the minimum and maximum employee IDs.
WITH employee_gaps AS (
    select emp_id,LEAD(emp_id) OVER (ORDER BY emp_id) AS next_emp_id
    from employees
)
select emp_id + 1 AS missing_emp_id
from employee_gaps
where next_emp_id > emp_id + 1;

--19.	Find salaries received by more than one employee:
select salary, COUNT(*) AS employee_count
from employees
group by salary
having count(*) > 1;

--20.	Find employees whose salary is not shared by any other employee. 
--Expected columns: emp_id emp_name salary:
select emp_id, emp_name, salary
from employees
where salary IN (
    select salary from employees
    group by salary
    having count(*) = 1);

--21.	Calculate the running total of sales ordered by sale_date. 
--Expected columns: sale_date amount running_total:
select sale_date, amount, SUM(amount) OVER (ORDER BY sale_date) AS running_total from sales
order by sale_date;

--22.	Display the current sale amount and the previous day's sale amount. 
--Expected columns: sale_date amount previous_amount:
select sale_date, amount, LAG(amount) OVER(ORDER BY sale_date) AS previous_amount from sales
order by sale_date;

--23.	Calculate the difference between the current month's sales and previous month's sales. 
--Expected columns: month total_sales previous_sales sales_difference
select month, total_sales, LAG(total_sales) OVER (ORDER BY month) AS previous_sales, total_sales - LAG(total_sales) OVER (ORDER BY month) AS sales_difference from monthly_sales
order by month;

--24.	Task: Find the first order placed by each customer. 
--Expected columns: customer_id order_id order_date amount:
select customer_id, MIN(order_date) AS first_order_date
from orders
group by customer_id;

--25.	Find the most recent order of every customer.
--Expected columns: customer_id order_id order_date amount:
WITH ranked_orders AS (
    select customer_id, order_id, order_date, amount,
    ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY order_date DESC ) AS rank from orders
)
select customer_id, order_id, order_date, amount
from ranked_orders
where rank = 1;

--26.	Find customers who have placed more than one order. 
--Expected columns: customer_id order_count:
select customer_id, COUNT(*) AS order_count
from orders
group by customer_id
having cont(*) > 1;

--27.	Find the third highest distinct salary:
WITH ranked_salaries AS (
    select salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS salary_rank
    from employees)
select distinct salary
from ranked_salaries
where salary_rank = 3;

--28.	Find products whose price is greater than the average product price. 
--Expected columns: product_id product_name price:
select product_id, product_name, price
from products
where price > (select AVG(price)from products);

--29.	Find the most expensive product in each category. 
--Expected columns: category product_name price:
WITH ranked_products AS (
    select category, product_name, price,
    ROW_NUMBER() OVER(PARTITION BY category ORDER BY price DESC ) AS rank
    from products)
select category, product_name, price
from ranked_products
WHERE rank = 1;

--30.	Find departments that have more than 3 employees. 
--Expected columns: department employee_count:
select department, COUNT(*) AS employee_count
from employees
group by department
having count(*) > 3;

--31.	Find employees whose salary is greater than their manager's salary. 
--Expected columns: emp_id emp_name employee_salary manager_salary:
select e.emp_id, e.emp_name, e.salary AS employee_salary, m.salary AS manager_salary from employees e
join employees m ON e.manager_id = m.emp_id
where e.salary > m.salary;

--32.	For each department, find the difference between the highest salary and lowest salary. 
--Expected columns: department max_salary min_salary salary_difference:
select department, max(salary) AS max_salary, min(salary) AS min_salary, max(salary) - min(salary) AS salary_difference
from employees
group by department;

--33.	Find customers who have purchased every available product. 
--Expected columns: customer_id customer_name:
select c.customer_id, c.customer_name
from customers c
join sales s ON c.customer_id = s.customer_id
group by c.customer_id, c.customer_name
having count(distinct s.product_id) = (select count(*) from products);

--34.	Task: Find the employee who has been working for the longest period. 
--Expected columns: emp_id emp_name joining_date:
select top 1 emp_id, emp_name, joining_date
from employees
order by joining_date ASC;

--35.	Task: Find all orders where the order amount is greater than the overall average order amount. 
--Expected columns: order_id customer_id amount:
select order_id, customer_id, amount
from orders
where amount > (select avg(amount) from orders);

--36.	Find the category that contains the maximum number of products. 
--Expected columns: category product_count:
select category, count(*) AS product_count
from products
group by category
having count(*) = (select max(product_count) from (select count(*) AS product_count from products group by category) t);

--37.	Find employees whose salary has not changed between the recorded salary periods. 
--Expected columns: emp_id salary:
select emp_id, min(salary) AS salary
from employee_salary_history
group by emp_id
having min(salary) = max(salary);

--38.	Find users who logged in on at least 3 consecutive days. 
--Expected columns: user_id:
WITH login_data AS (select user_id, login_date, LAG(login_date) OVER(PARTITION BY user_id ORDER BY login_date) AS previous_date,
        LAG(login_date, 2) OVER(PARTITION BY user_id ORDER BY login_date) AS previous_2_date
    from user_logins
)
select distnict user_id
from login_data
where DATEDIFF(DAY, previous_date, login_date) = 1 and DATEDIFF(DAY, previous_2_date, login_date) = 2;

--39.	Find the second order placed by each customer. 
--Expected columns: customer_id order_id order_date amount:
WITH ranked_orders AS (
    select customer_id, order_id, order_date,amount,
    ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY order_date) AS rank
    from orders)
select customer_id, order_id, order_date, amount
from ranked_orders
where rank = 2;

--40.	Calculate each department's total salary and its percentage contribution to the company's total salary.
--Expected columns: department department_salary total_company_salary percentage_contribution:
WITH department_salary AS (
    select department, SUM(salary) AS department_salary
    from employees
    group by department)
select department, department_salary, SUM(department_salary) OVER() AS total_company_salary,
    round(department_salary * 100.0 / SUM(department_salary) OVER (),2
    ) AS percentage_contribution
from department_salary;

--41.	Display the complete employee hierarchy, starting from the top-level manager. 
--Expected columns: emp_id emp_name manager_id level:
WITH EmployeeHierarchy AS
(select emp_id, emp_name, manager_id, 1 AS level
 from employees
 where manager_id IS NULL
UNION ALL
SELECT e.emp_id, e.emp_name, e.manager_id, eh.level + 1 AS level
from employees e
inner join EmployeeHierarchy eh ON e.manager_id = eh.emp_id
)
select emp_id, emp_name, manager_id, level
from EmployeeHierarchy
order by level, emp_id;

--42.	Find employees whose salary increased at every recorded salary change. 
--Expected columns: emp_id:
WITH salary_data AS (
    select emp_id, salary_date, salary, LAG(salary) OVER(PARTITION BY emp_id ORDER BY salary_date) AS previous_salary
    from salary_history)
select emp_id from salary_data
group by emp_id
having count(*) = count(previous_salary)
   and SUM(CASE WHEN salary > previous_salary THEN 1 ELSE 0 END) = COUNT(*) -1;

--43.	Calculate each customer's yearly revenue and return the top 3 customers for each year. 
--Expected columns: year customer_id total_revenue rank:
WITH yearly_revenue AS (
    select year(order_date) AS year, customer_id, sum(amount) AS total_revenue
    from orders
    group by year(order_date), customer_id
),
ranked_customers AS (
    select year, customer_id, total_revenue, DENSE_RANK() OVER(PARTITION BY year ORDER BY total_revenue DESC) AS rank
    from yearly_revenue)
select year, customer_id, total_revenue, rank
from ranked_customers
where rank <= 3
order by year, rank;

--44.	Find all dates where no sales record exists between the minimum and maximum sale dates. 
--Expected result: 2026-01-03, 2026-01-05:
WITH RECURSIVE DateRange AS
(select min(sale_date) AS sale_date
 from daily_sales

UNION ALL

select DATE_ADD(sale_date, INTERVAL 1 DAY)
from DateRange
where sale_date < (select max(sale_date) from daily_sales)
)
select d.sale_date
from DateRange d
left join daily_sales s ON d.sale_date = s.sale_date
where s.sale_date IS NULL;

--45.	For each user, find their longest consecutive login streak. 
--Expected columns: user_id longest_streak:
WITH numbered_logins AS (
select user_id, login_date, ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY login_date) AS rank
from user_logins
),
login_groups AS (
select user_id, login_date, DATE_SUB(login_date, INTERVAL rn DAY) AS grp
from numbered_logins
),
streaks AS (
    select user_id, grp, COUNT(*) AS streak_length
    from login_groups
    group by user_id, grp
)
select user_id, MAX(streak_length) AS longest_streak
from streaks
group by user_id;

--46.	Find pairs of customers who purchased exactly the same set of products. 
--Expected columns: customer_1 customer_2:
WITH customer_products AS (
    select customer_id,GROUP_CONCAT(DISTINCT product_id ORDER BY product_id) AS product_list,
    COUNT(DISTINCT product_id) AS product_count
    from sales
    group by customer_id
)
select c1.customer_id AS customer_1, c2.customer_id AS customer_2
from customer_products c1
join customer_products c2 ON c1.customer_id < c2.customer_id
and c1.product_count = c2.product_count
and c1.product_list = c2.product_list;

--47.	Calculate the running sales amount and the running percentage of total sales. 
--Expected columns: sale_date amount running_total running_percentage:
select sale_date, amount, SUM(amount) OVER(ORDER BY sale_date) AS running_total,
round(SUM(amount) OVER(ORDER BY sale_date) * 100.0 / SUM(amount) OVER (),2) AS running_percentage
from sales
order by sale_date;

--48.	Find customers whose spending increased every month:
WITH spending_data AS (
    select customer_id, month, amount,
LAG(amount) OVER(PARTITION BY customer_id
            ORDER BY CASE month
                    WHEN 'January' THEN 1
                    WHEN 'February' THEN 2
                    WHEN 'March' THEN 3
                    WHEN 'April' THEN 4
                    WHEN 'May' THEN 5
                    WHEN 'June' THEN 6
                    WHEN 'July' THEN 7
                    WHEN 'August' THEN 8
                    WHEN 'September' THEN 9
                    WHEN 'October' THEN 10
                    WHEN 'November' THEN 11
                    WHEN 'December' THEN 12
                END) AS previous_amount
    from customer_monthly_sales
)
select customer_id
from spending_data
group by customer_id
having sum(
    CASE
        WHEN previous_amount IS NOT NULL
             AND amount <= previous_amount
        THEN 1
        ELSE 0
    END
) = 0;

--49.	Find the median salary of all employees:
WITH ranked_salary AS (
    select salary, ROW_NUMBER() OVER (ORDER BY salary) AS rank,
    COUNT(*) OVER () AS total_count
    from employees
)
select AVG(salary) AS median_salary
from ranked_salary
where rank IN (FLOOR((total_count + 1) / 2), FLOOR((total_count + 2) / 2)
);

--50.	Find customers who placed at least 3 orders, and display the first order date, last order date, and number of days between them. 
--Expected columns: customer_id customer_name order_count first_order_date last_order_date days_between_orders:
select c.customer_id, c.customer_name, count(o.order_id) AS order_count, min(o.order_date) AS first_order_date,
max(o.order_date) AS last_order_date,
DATEDIFF(max(o.order_date), min(o.order_date)) AS days_between_orders
from customers c
join orders o ON c.customer_id = o.customer_id
group by c.customer_id, c.customer_name
having count(o.order_id) >= 3;



